//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.12 at 09:45:21 AM EDT 
//


package org.netbeans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "l10n")
public class L10N {

    @XmlAttribute(name = "langcode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String langcode;
    @XmlAttribute(name = "brandingcode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String brandingcode;
    @XmlAttribute(name = "module_spec_version")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String moduleSpecVersion;
    @XmlAttribute(name = "module_major_version")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String moduleMajorVersion;
    @XmlAttribute(name = "OpenIDE-Module-Name")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String openIDEModuleName;
    @XmlAttribute(name = "OpenIDE-Module-Long-Description")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String openIDEModuleLongDescription;

    /**
     * Gets the value of the langcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLangcode() {
        return langcode;
    }

    /**
     * Sets the value of the langcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLangcode(String value) {
        this.langcode = value;
    }

    /**
     * Gets the value of the brandingcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrandingcode() {
        return brandingcode;
    }

    /**
     * Sets the value of the brandingcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrandingcode(String value) {
        this.brandingcode = value;
    }

    /**
     * Gets the value of the moduleSpecVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModuleSpecVersion() {
        return moduleSpecVersion;
    }

    /**
     * Sets the value of the moduleSpecVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModuleSpecVersion(String value) {
        this.moduleSpecVersion = value;
    }

    /**
     * Gets the value of the moduleMajorVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModuleMajorVersion() {
        return moduleMajorVersion;
    }

    /**
     * Sets the value of the moduleMajorVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModuleMajorVersion(String value) {
        this.moduleMajorVersion = value;
    }

    /**
     * Gets the value of the openIDEModuleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpenIDEModuleName() {
        return openIDEModuleName;
    }

    /**
     * Sets the value of the openIDEModuleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpenIDEModuleName(String value) {
        this.openIDEModuleName = value;
    }

    /**
     * Gets the value of the openIDEModuleLongDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpenIDEModuleLongDescription() {
        return openIDEModuleLongDescription;
    }

    /**
     * Sets the value of the openIDEModuleLongDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpenIDEModuleLongDescription(String value) {
        this.openIDEModuleLongDescription = value;
    }

}
