//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.12 at 09:45:21 AM EDT 
//


package org.netbeans;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "description",
    "moduleNotification",
    "externalPackage",
    "manifestOrL10N"
})
@XmlRootElement(name = "module")
public class Module {

    @XmlAttribute(name = "codenamebase", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String codenamebase;
    @XmlAttribute(name = "homepage")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String homepage;
    @XmlAttribute(name = "distribution", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String distribution;
    @XmlAttribute(name = "license")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String license;
    @XmlAttribute(name = "downloadsize", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String downloadsize;
    @XmlAttribute(name = "needsrestart")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String needsrestart;
    @XmlAttribute(name = "moduleauthor")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String moduleauthor;
    @XmlAttribute(name = "releasedate")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String releasedate;
    @XmlAttribute(name = "global")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String global;
    @XmlAttribute(name = "targetcluster")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String targetcluster;
    @XmlAttribute(name = "eager")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String eager;
    @XmlAttribute(name = "autoload")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String autoload;
    protected String description;
    @XmlElement(name = "module_notification")
    protected String moduleNotification;
    @XmlElement(name = "external_package")
    protected List<ExternalPackage> externalPackage;
    @XmlElements({
        @XmlElement(name = "manifest", required = true, type = Manifest.class),
        @XmlElement(name = "l10n", required = true, type = L10N.class)
    })
    protected List<Object> manifestOrL10N;

    /**
     * Gets the value of the codenamebase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodenamebase() {
        return codenamebase;
    }

    /**
     * Sets the value of the codenamebase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodenamebase(String value) {
        this.codenamebase = value;
    }

    /**
     * Gets the value of the homepage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHomepage() {
        return homepage;
    }

    /**
     * Sets the value of the homepage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHomepage(String value) {
        this.homepage = value;
    }

    /**
     * Gets the value of the distribution property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDistribution() {
        return distribution;
    }

    /**
     * Sets the value of the distribution property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDistribution(String value) {
        this.distribution = value;
    }

    /**
     * Gets the value of the license property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicense() {
        return license;
    }

    /**
     * Sets the value of the license property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicense(String value) {
        this.license = value;
    }

    /**
     * Gets the value of the downloadsize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDownloadsize() {
        return downloadsize;
    }

    /**
     * Sets the value of the downloadsize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDownloadsize(String value) {
        this.downloadsize = value;
    }

    /**
     * Gets the value of the needsrestart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNeedsrestart() {
        return needsrestart;
    }

    /**
     * Sets the value of the needsrestart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNeedsrestart(String value) {
        this.needsrestart = value;
    }

    /**
     * Gets the value of the moduleauthor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModuleauthor() {
        return moduleauthor;
    }

    /**
     * Sets the value of the moduleauthor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModuleauthor(String value) {
        this.moduleauthor = value;
    }

    /**
     * Gets the value of the releasedate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReleasedate() {
        return releasedate;
    }

    /**
     * Sets the value of the releasedate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReleasedate(String value) {
        this.releasedate = value;
    }

    /**
     * Gets the value of the global property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGlobal() {
        return global;
    }

    /**
     * Sets the value of the global property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGlobal(String value) {
        this.global = value;
    }

    /**
     * Gets the value of the targetcluster property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetcluster() {
        return targetcluster;
    }

    /**
     * Sets the value of the targetcluster property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetcluster(String value) {
        this.targetcluster = value;
    }

    /**
     * Gets the value of the eager property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEager() {
        return eager;
    }

    /**
     * Sets the value of the eager property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEager(String value) {
        this.eager = value;
    }

    /**
     * Gets the value of the autoload property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutoload() {
        return autoload;
    }

    /**
     * Sets the value of the autoload property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoload(String value) {
        this.autoload = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the moduleNotification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModuleNotification() {
        return moduleNotification;
    }

    /**
     * Sets the value of the moduleNotification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModuleNotification(String value) {
        this.moduleNotification = value;
    }

    /**
     * Gets the value of the externalPackage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the externalPackage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExternalPackage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExternalPackage }
     * 
     * 
     */
    public List<ExternalPackage> getExternalPackage() {
        if (externalPackage == null) {
            externalPackage = new ArrayList<ExternalPackage>();
        }
        return this.externalPackage;
    }

    /**
     * Gets the value of the manifestOrL10N property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the manifestOrL10N property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getManifestOrL10N().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Manifest }
     * {@link L10N }
     * 
     * 
     */
    public List<Object> getManifestOrL10N() {
        if (manifestOrL10N == null) {
            manifestOrL10N = new ArrayList<Object>();
        }
        return this.manifestOrL10N;
    }

}
